language: node_js
node_js: node
cache:
  directories:
  - /home/travis/.elm
  - node_modules
  - elm-stuff
branches:
  only:
  - master
install:
- npm install -g elm@latest uglify-js@latest
- curl -OL http://dl.itch.ovh/butler/linux-amd64/head/butler
- chmod +x butler
script:
- "./scripts/deploy.sh"
notifications:
  email:
    recipients:
    - martin@janiczek.cz
